### ISSUE TITLE
多类别分割问题

### ISSUE THREAD

**Issue by ManuJuice** [McGregorWwww/UDTransNet#5]
您好，我是从UCTransNet过来的

我现在想要做一个多类别的分割任务，目标类别有三种，在标签中分别用红黄绿三种颜色进行标注，此外背景是黑色的

我初步阅读了UDTransNet的代码之后，发现Load_Dataset.py文件中，对于标签的读取似乎都是进行了灰度处理并且最终转为黑白图，只有Synapse是支持多分类的，但是我的数据集是png格式的，与Synapse数据集的格式不同，请问我应该如何对代码和数据集进行修改？

**Comment by McGregorWwww** [comment]
你好，你可以基于png数据集比如ISIC进行修改，只需要把标签转换一下就好了。

对于标签读取需要修改为3通道读取，然后转换标签，比如if 红 [255,0,0], label = 1 ...

希望有帮助，祝好运

**Comment by ManuJuice** [comment]
> 你好，你可以基于png数据集比如ISIC进行修改，只需要把标签转换一下就好了。
> 
> 对于标签读取需要修改为3通道读取，然后转换标签，比如if 红 [255,0,0], label = 1 ...
> 
> 希望有帮助，祝好运

谢谢，可以训练了！
不给还有个问题想请教一下：因为我有3个目标种类，此外还有一个黑色的背景，将n_labels设为3后，训练会报错
RuntimeError: cuda runtime error (710) : device-side assert trigger

上网搜到的结果是标签数出了问题，但是将其改为4后，可以正常训练，不过现在结果还没出来，我也不知道训练结果是否正确；
所以我不太明白这个n_labels指的是什么，因为做二分类时，n_labels=1，可以正常训练，多分类时应该加上多出的类别数就好，为什么会报错呢？

②这个模型是不是不能使用已训练的模型继续训练？

**Comment by McGregorWwww** [comment]
不客气，
1. 二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
2. 可以的，训练前加载一下就好了

**Comment by ManuJuice** [comment]
> 不客气，
> 
> 1. 二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
> 2. 可以的，训练前加载一下就好了

好的，感谢您的解答！

**Comment by 2561995604** [comment]
> > 不客气，
> > 
> > 1. 二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
> > 2. 可以的，训练前加载一下就好了
> 
> 好的，感谢您的解答！

请问您的多类别分割对于训练和测试以及数据的加载做了哪些改动，我也要做一个多类别的分割。

**Comment by ManuJuice** [comment]
> > > 不客气，
> > > 
> > > 1. 二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
> > > 2. 可以的，训练前加载一下就好了
> > 
> > 
> > 好的，感谢您的解答！
> 
> 请问您的多类别分割对于训练和测试以及数据的加载做了哪些改动，我也要做一个多类别的分割。

你好，代码是很久前改的，记忆有些模糊，只想起来这些：
①可以参考上述问答中的方法，读取数据、转换标签时修改通道数，注意n_labels的值；
②然后在生成GT那里可能也有一些要改的，应该是跟数据格式的转换以及处理数据的库有关；
③验证那里的代码应该也需要修改，我记得是跟类别数量有关的。
祝顺利！

**Comment by 2561995604** [comment]
> > > > 不客气，
> > > > 
> > > > 1. 二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
> > > > 2. 可以的，训练前加载一下就好了
> > > 
> > > 
> > > 好的，感谢您的解答！
> > 
> > 
> > 请问您的多类别分割对于训练和测试以及数据的加载做了哪些改动，我也要做一个多类别的分割。
> 
> 你好，代码是很久前改的，记忆有些模糊，只想起来这些： ①可以参考上述问答中的方法，读取数据、转换标签时修改通道数，注意n_labels的值； ②然后在生成GT那里可能也有一些要改的，应该是跟数据格式的转换以及处理数据的库有关； ③验证那里的代码应该也需要修改，我记得是跟类别数量有关的。 祝顺利！

谢谢您的意见。

**Comment by DanpengDing** [comment]
> > 你好，你可以基于png数据集比如ISIC进行修改，只需要把标签转换一下就好了。
> > 对于标签读取需要修改为3通道读取，然后转换标签，比如if 红 [255,0,0], label = 1 ...
> > 希望有帮助，祝好运
> 
> 谢谢，可以训练了！ 不过还有个问题想请教一下：因为我有3个目标种类，此外还有一个黑色的背景，将n_labels设为3后，训练会报错 RuntimeError: cuda runtime error (710) : device-side assert trigger
> 
> 上网搜到的结果是标签数出了问题，但是将其改为4后，可以正常训练，不过现在结果还没出来，我也不知道训练结果是否正确； 所以我不太明白这个n_labels指的是什么，因为做二分类时，n_labels=1，可以正常训练，多分类时应该加上多出的类别数就好，为什么会报错呢？
> 
> ②这个模型是不是不能使用已训练的模型继续训练？

你好，请问你可以训练了吗。我换了个模型虽然可以训练，但在计算损失函数的时候RuntimeError: cuda runtime error (710) : device-side assert trigger也遇到了这个问题，请问您由解决办法吗？

**Comment by ManuJuice** [comment]
> > > 你好，你可以基于png数据集比如ISIC进行修改，只需要把标签转换一下就好了。
> > > 对于标签读取需要修改为3通道读取，然后转换标签，比如if 红 [255,0,0], label = 1 ...
> > > 希望有帮助，祝好运
> > 
> > 
> > 谢谢，可以训练了！ 不过还有个问题想请教一下：因为我有3个目标种类，此外还有一个黑色的背景，将n_labels设为3后，训练会报错 RuntimeError: cuda runtime error (710) : device-side assert trigger
> > 上网搜到的结果是标签数出了问题，但是将其改为4后，可以正常训练，不过现在结果还没出来，我也不知道训练结果是否正确； 所以我不太明白这个n_labels指的是什么，因为做二分类时，n_labels=1，可以正常训练，多分类时应该加上多出的类别数就好，为什么会报错呢？
> > ②这个模型是不是不能使用已训练的模型继续训练？
> 
> 你好，请问你可以训练了吗。我换了个模型虽然可以训练，但在计算损失函数的时候RuntimeError: cuda runtime error (710) : device-side assert trigger也遇到了这个问题，请问您由解决办法吗？

你好，以下是作者的回答，你可以参考一下：

二分类和多分类是不同的。二分类中最后的激活函数是sigmoid，因此模型可以输出一个通道的prob map，只需要筛选>0.5的作为前景就可以；多分类时为softmax，最好考虑背景类，所以n_labels+1
